apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: petclinic
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/PiyushVerma2197/Terraform-multicloud.git
    targetRevision: main
    path: spring-petclinic/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
