name: Deploy PetClinic

on:
  workflow_run:
    workflows:
      - Terraform Infrastructure
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Configure kubectl
      #   run: |
      #     aws eks update-kubeconfig \
      #       --region "$AWS_REGION" \
      #       --name "$(terraform output -raw eks_cluster_name)"

      # - name: Verify cluster
      #   run: |
      #     kubectl get nodes
      #     kubectl get pods -A


      - name: Configure kubectl for EKS
        shell: bash
        run: |
         set -e

         echo "AWS Region: $AWS_REGION"

         echo "Available EKS clusters:"
         aws eks list-clusters \
         --region "$AWS_REGION"

         CLUSTER_NAME=$(aws eks list-clusters \
         --region "$AWS_REGION" \
         --query 'clusters[0]' \
         --output text)

         echo "Cluster name: $CLUSTER_NAME"

         if [ -z "$CLUSTER_NAME" ] || [ "$CLUSTER_NAME" = "None" ]; then
          echo "ERROR: EKS cluster was not found."
          exit 1
         fi

         echo "Updating kubeconfig..."

         aws eks update-kubeconfig \
         --region "$AWS_REGION" \
         --name "$CLUSTER_NAME"
         
         echo "Kubeconfig created successfully."
         
         echo "Current kubeconfig:"
         
         kubectl config view --minify
         echo "Current context:"
         kubectl config current-context

      - name: Verify EKS connection
        shell: bash
        run: |
         echo "KUBECONFIG=$KUBECONFIG"

         echo "Current context:"
         kubectl config current-context

         echo "Cluster information:"
         kubectl cluster-info

         echo "Nodes:"
         kubectl get nodes

      # - name: Install/Update NGINX Ingress
      #   run: |
      #     helm upgrade --install ingress-nginx \
      #       ingress-nginx/ingress-nginx \
      #       --repo https://kubernetes.github.io/ingress-nginx \
      #       --namespace ingress-nginx \
      #       --create-namespace \
      #       --set controller.service.type=NodePort \
      #       --set controller.service.nodePorts.http=32652

      - name: Install/Update NGINX Ingress
        run: |
          helm upgrade --install ingress-nginx \
           ingress-nginx \
           --repo https://kubernetes.github.io/ingress-nginx \
           --namespace ingress-nginx \
           --create-namespace \
           --set controller.service.type=NodePort \
           --set controller.service.nodePorts.http=32652

      - name: Apply PetClinic
        run: |
          kubectl apply -f spring-petclinic/k8s/petclinic.yml

      - name: Wait for PetClinic
        run: |
          kubectl rollout status \
            deployment/petclinic \
            --timeout=300s

      - name: Verify PetClinic
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
