name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
   
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check GitHub OIDC environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Workflow: $GITHUB_WORKFLOW"  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select or create Terraform workspace
        run: |
         WORKSPACE="dev"

         if terraform workspace list | grep -E "^[* ]+$WORKSPACE$" > /dev/null; then
           echo "Workspace '$WORKSPACE' already exists. Selecting it..."
           terraform workspace select "$WORKSPACE"
         else
           echo "Workspace '$WORKSPACE' does not exist. Creating it..."
           terraform workspace new "$WORKSPACE"
         fi

         echo "Current workspace:"
         terraform workspace show

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -target=module.aws_vpc \
            -out=tfplan

      - name: Verify Terraform Plan
        run: |
          terraform show -no-color tfplan      

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -target=module.aws_vpc -auto-approve tfplan

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$(terraform output -raw eks_cluster_name)"

      - name: Verify cluster
        run: |
          kubectl get nodes
          kubectl get pods -A

      - name: Terraform Plan
        run: |
           terraform plan \
           -target=helm_release.nginx_ingress \
           -target=kubernetes_secret_v1.petclinic_rds \
           -target=kubernetes_deployment_v1.ingress_healthcheck \
           -target=kubernetes_service_v1.ingress_healthcheck \
           -out=k8s.tfplan

      - name: Terraform Apply for Kuberenetes Resources
        run: |
           terraform apply \
           -target=helm_release.nginx_ingress \
           -target=kubernetes_secret_v1.petclinic_rds \
           -target=kubernetes_deployment_v1.ingress_healthcheck \
           -target=kubernetes_service_v1.ingress_healthcheck -auto-approve k8s.tfplan
           
         
