name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.terraform.lock.hcl'
      - '.github/workflows/terraform.yaml'

  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.terraform.lock.hcl'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check GitHub OIDC environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Workflow: $GITHUB_WORKFLOW"  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select dev workspace
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -target=module.aws_vpc \
            -target=helm_release.nginx_ingress \
            -target=kubernetes_secret_v1.petclinic_rds \
            -target=kubernetes_deployment_v1.ingress_healthcheck \
            -target=kubernetes_service_v1.ingress_healthcheck \
            -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
